name: run-tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
  phpunit:
    name: PhpUnit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: svikramjeet/git-action-laravel-phpunit@master
    
  check-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: glassmonkey/actions-php-audit@v0.1.1
        id: checker # id is required if called from other steps
      # Todo other actions
      - name: sample message
        run: echo "${{ steps.checker.outputs.message }}"
